// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('ibnsina').directive("onlineStatus", [
    function() {
      return {
        restrict: "A",
        transclude: true,
        templateUrl: 'scripts/directives/online-status/online-status.html',
        scope: {
          map: '=',
          prefix: '=',
          user: '='
        }
      };
    }
  ]);

}).call(this);
