// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('ibnsina').directive("accessStatus", [
    function() {
      return {
        restrict: "A",
        templateUrl: 'scripts/directives/access-status/access-status.html',
        scope: {
          map: '=',
          prefix: '=',
          user: '=',
          room: '=',
          add: '&',
          remove: '&'
        },
        controller: ["$scope", "$element", function(scope, elm) {}],
        link: function(scope, elm, attrs) {
          scope.addFn = function() {
            scope.add({
              user: scope.user,
              room: scope.room
            });
          };
          scope.removeFn = function() {
            scope.remove({
              user: scope.user,
              room: scope.room
            });
          };
        }
      };
    }
  ]);

}).call(this);
