// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('ibnsina').directive("selectRadio", [
    "$cookies", function($cookies) {
      return {
        restrict: "EA",
        templateUrl: 'scripts/directives/select.radio/select.radio.html',
        scope: {
          'model': '=',
          'list': '='
        },
        controller: function($scope, $element) {},
        link: function(scope, elm, attrs) {
          scope.select = function(item) {
            scope.model = item.value;
          };
        }
      };
    }
  ]);

}).call(this);
