// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('ibnsina').directive("inputNumber", [
    "$cookies", function($cookies) {
      return {
        restrict: "EA",
        transclude: true,
        templateUrl: 'scripts/directives/input.number/input.number.html',
        scope: {
          'name': '@',
          'validator': '=',
          'model': '=',
          'label': '@',
          'min': '=',
          'max': '='
        },
        controller: function($scope, $element) {},
        link: function(scope, elm, attrs) {}
      };
    }
  ]);

}).call(this);
