// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('ibnsina').controller('UsersCtrl', [
    '$scope', '$state', '$rootScope', '$api', 'Restangular', 'notify', '$security', '$mode', function($scope, $state, $rootScope, $api, Restangular, notify, $security, $mode) {
      var fetch, fetchRoles, fetchUserRoles;
      console.log('UsersCtrl');
      $rootScope.current = 'users';
      $security.loadSecurity(function() {
        var isAdmin;
        isAdmin = $security.hasRole('ADMIN');
        if (!isAdmin) {
          return $state.transitionTo('error-access');
        }
      });
      $scope.map = [];
      $scope.map['roles'] = [];
      $scope.model = {
        user: {
          login: null,
          name: null
        }
      };
      $scope.$watch(function() {
        return $scope.model.user.login;
      }, function(newvalue, oldvalue) {
        var patt;
        $scope.loginInvalid = false;
        patt = new RegExp("^[a-z]+(\.[a-z]+)?$");
        if (!patt.test(newvalue)) {
          $scope.loginInvalid = true;
        }
      });
      fetch = function() {
        $api.user.list(function(data) {
          $scope.users = data.plain();
          $scope.users.sort(function(a, b) {
            return a.name.localeCompare(b.name);
          });
          if ($scope.users.length > 0) {
            fetchUserRoles(0);
          }
          $mode.change('list');
          fetchRoles();
        });
      };
      fetchUserRoles = function(index) {
        var userId;
        userId = $scope.users[index].id;
        $api.user.roles(userId, function(dataRoles) {
          $scope.map['roles']['u' + userId] = dataRoles;
          if (index < ($scope.users.length - 1)) {
            fetchUserRoles(index + 1);
          }
        });
      };
      fetch();
      $scope.add = function(user) {
        $api.user.create(user, function(data) {
          notify({
            message: 'Пользователь ' + user.name + ' успешно добавлен',
            classes: 'alert-success'
          });
          $scope.users = data;
          fetch();
        }, function(err) {
          notify({
            message: 'Пользователь ' + user.name + ' не был добавлен',
            classes: 'alert-warning'
          });
        });
      };
      $scope.roles = [];
      fetchRoles = function() {
        $api.secure.role.list(function(data) {
          var d, _i, _len, _ref;
          console.log(data.plain());
          $scope.roles = [];
          _ref = data.plain();
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            d = _ref[_i];
            $scope.roles.push(d.field.value);
          }
          console.log($scope.roles);
          $scope.roles;
        });
      };
    }
  ]);

}).call(this);
