// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('ibnsina').service('$api', [
    '$rootScope', 'Restangular', function($rootScope, Restangular) {
      var crud;
      Restangular.setErrorInterceptor(function(response, deferred, responseHandler) {
        if (response.status === 200) {
          return false;
        }
        if (response.status = 403) {
          if (window.location.pathname.indexOf('index.html') !== -1) {
            return window.location = domainURL + '/api/login.html';
          }
        }
        return true;
      });
      crud = {
        list: function(process) {
          Restangular.all(this.url).getList().then(function(data) {
            process(data);
          });
        },
        get: function(id, process) {
          Restangular.one(this.url, id).get().then(function(data) {
            process(data);
          });
        },
        create: function(plain, process) {
          Restangular.all(this.url).post(plain).then(function(data) {
            process(data);
          });
        },
        update: function(plain, process) {
          Restangular.one(this.url, plain.id).customPUT(plain).then(function(data) {
            process(data);
          });
        },
        "delete": function(id, process) {
          Restangular.one(this.url, id).remove({}).then(function(data) {
            process(data);
          });
        }
      };
      this.core = {
        authorized: function(process) {
          Restangular.one('authorized').get().then(function(data) {
            process(data);
          });
        }
      };
      this.openapi = {
        url: 'openapi',
        register: function(plain, process) {
          Restangular.all(this.url + '/register').post(plain).then(function(data) {
            process(data);
          });
        }
      };
      this.secure = {
        role: angular.copy(crud)
      };
      this.secure.role.url = 'secure/roles';
      this.user = angular.copy(crud);
      this.user.url = 'secure/users';
      this.user.current = function(process) {
        Restangular.one(this.url + '/current').get().then(function(data) {
          process(data.plain());
        });
      };
      this.user.roles = function(id, process) {
        Restangular.all(this.url + '/' + id + '/roles').getList().then(function(data) {
          process(data.plain());
        });
      };
      this.user.logout = function(process) {
        Restangular.one(this.url + '/logout').get().then(function(data) {
          process(data);
        });
      };
      this.room = angular.copy(crud);
      this.room.url = 'secure/rooms';
      this.room.users = {
        url: 'secure/rooms',
        list: function(id, process) {
          Restangular.all(this.url + '/' + id + '/users').getList().then(function(data) {
            process(data.plain());
          });
        },
        create: function(id, plain, process) {
          Restangular.all(this.url + '/' + id + '/users').post(plain).then(function(data) {
            process(data);
          });
        },
        "delete": function(id, userId, process) {
          Restangular.one(this.url + '/' + id + '/users', userId).remove({}).then(function(data) {
            process(data);
          });
        },
        message: {
          send: function(plain, process) {
            Restangular.all('secure/rooms/' + plain.roomId + '/users/' + plain.userId + '/message').post(plain).then(function(data) {
              process(data);
            });
          }
        }
      };
      $rootScope.$api = this;
    }
  ]);

}).call(this);
