// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('ibnsina').service('$auth', [
    '$rootScope', '$cookies', '$api', '$security', function($rootScope, $cookies, $api, $security) {
      var fetchCurrent;
      this.authorized = function(fnAuthorized, fnNot) {
        $api.core.authorized(function(data) {
          if (data === 'true') {
            return fnAuthorized();
          } else {
            fnNot();
            return $rootScope.covering = false;
          }
        });
      };
      fetchCurrent = function() {
        $api.user.current(function(data) {
          $cookies.put('userId', data.id);
          $cookies.put('login', data.login);
          $security.loadSecurity();
        });
      };
      this.authenticate = function() {
        $api.core.authorized(function(data) {
          if (data === 'true') {
            $cookies.put('auth', true);
            fetchCurrent();
            $rootScope.covering = false;
          } else {
            $cookies.put('auth', false);
            window.location = domainURL + '/api/login.html';
          }
        });
      };
      this.logout = function() {
        $api.user.logout(function(data) {
          if (data.field.value) {
            $cookies.put('auth', false);
            location.reload();
          }
        });
      };
      $rootScope.$auth = this;
    }
  ]);

}).call(this);
