// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('ibnsina').service('$clock', [
    '$rootScope', '$scope', '$interval', function($rootScope, $scope, $interval) {
      $rootScope.res = new Date();
      this.init = function() {
        $interval(function() {
          $rootScope.res = new Date();
        }, 1000);
      };
      $rootScope.$clock = this;
    }
  ]);

}).call(this);
