// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('ibnsina').service('$mode', [
    '$rootScope', function($rootScope) {
      var current;
      current = null;
      this.current = function() {
        return current;
      };
      this.change = function(mode) {
        current = mode;
      };
      $rootScope.$mode = this;
    }
  ]);

}).call(this);
