// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('ibnsina').service('$security', [
    '$rootScope', '$state', '$cookies', 'Restangular', '$api', function($rootScope, $state, $cookies, Restangular, $api) {
      var hasRoleFn, roles;
      roles = [];
      hasRoleFn = function(roleName) {
        var hasRole, role, _i, _len;
        hasRole = false;
        if (roles && roles.length > 0) {
          for (_i = 0, _len = roles.length; _i < _len; _i++) {
            role = roles[_i];
            if (role.name === roleName) {
              hasRole = true;
              break;
            }
          }
        }
        return hasRole;
      };
      this.hasRole = hasRoleFn;
      this.loadSecurity = function(fn) {
        var userId;
        userId = $cookies.get('userId');
        $api.user.roles(userId, function(data) {
          var isAdmin, isGuest;
          roles = data;
          if (fn) {
            fn();
          } else {
            isAdmin = hasRoleFn('ADMIN');
            isGuest = hasRoleFn('GUEST');
            if (isGuest) {
              $state.transitionTo('room');
            } else if (isAdmin) {
              $state.transitionTo('room');
            }
          }
        });
      };
      $rootScope.$security = this;
    }
  ]);

}).call(this);
